#!/usr/bin/php -q
<?

/* Configuration Options */

$HOSTNAME = 'localhost';
$db = 'dhcp';
$db_user = 'dhcpuser';
$db_user_pass = '************';

$wireless_iface = "vlan7";
$wireless_ltime = "86400";
$config_file_path = '/tmp';

$default_domain = "darienlibrary.org";

/* No need to change anything below here */

$now = time();
$date = date('m-d-Y  H:i:s',$now);

mysql_connect("$HOSTNAME", "$db_user", "$db_user_pass");
mysql_select_db("$db");

$dhcfile = fopen($config_file_path . '/dhcpd.conf', "w+");
fputs($dhcfile, "####\n# Automatically generated dhcpd.conf file.\n# Created on $date\n#\n"); 
fputs($dhcfile, "# Important!  Do not edit this file.  Any changes you make will be overwritten!\n#\n####\n\n");


fputs($dhcfile, "# Global Options\n\n");
$sql1 = "select * from global_options";
$result1 = mysql_query($sql1);
while ($global_list = mysql_fetch_array($result1)) {
	fputs($dhcfile, "$global_list[1];\n");
}
fputs($dhcfile, "\n\n");

$sql2 = "select * from subnets order by id asc";
$result2 = mysql_query($sql2);
while ($subnet_list = mysql_fetch_array($result2)) {
	$id = $subnet_list[0];
	$network_name = $subnet_list[1];
	$network_iface = $subnet_list[2];
	$network_id = $subnet_list[3];
	$netmask = $subnet_list[4];
	$def_gateway = $subnet_list[5];
	$broadcast = $subnet_list[6];
	$dns1 = $subnet_list[7];
	$dns2 = $subnet_list[8];
	$lease_time = $subnet_list[9];
		
	fputs($dhcfile, "# $network_iface - $network_name\n#\n\n");
	fputs($dhcfile, "subnet $network_id netmask $netmask {\n");
	$sql3 = "select * from ranges where id = '$id' order by first asc";
	$result3 = mysql_query($sql3);
	while ($range_list = mysql_fetch_array($result3)) {
		$first = $range_list[2];
		$last = $range_list[3];
		fputs($dhcfile, "  range $first $last;\n");
	}
	fputs($dhcfile, "  option subnet-mask $netmask;\n");
	fputs($dhcfile, "  option broadcast-address $broadcast;\n");
	fputs($dhcfile, "  option routers $def_gateway;\n");
	if (($dns1) && (!($dns2))) { fputs($dhcfile, "  option domain-name-servers $dns1;\n"); }
	if (($dns1) && ($dns2)) { fputs($dhcfile, "  option domain-name-servers $dns1, $dns2;\n"); }
	if ($lease_time) {
		fputs($dhcfile, "  default-lease-time $lease_time;\n  max-lease-time $lease_time;\n");
	}
	fputs($dhcfile, "\n");
	
	$sql4 = "select * from reservations where subnet_id = '$id' order by hostname asc";
	$result4 = mysql_query($sql4);
	if (mysql_num_rows($result4) > 0) {
		fputs($dhcfile, "  ###[ Address reservations for $network_name ]###\n\n");
		if ($network_iface == $wireless_iface) {
			fputs($dhcfile, "  group {\n\n    default-lease-time $wireless_ltime;\n    max-lease-time $wireless_ltime;\n\n");
		}
		while ($res_list = mysql_fetch_array($result4)) {
			$mac = "";
			for($i = 0; $i < strlen($res_list[1]); $i+=2) $mac .= substr($res_list[1], $i, 2) . ":";
			$mac = substr($mac, 0, -1);
			$ip = $res_list[2];
			$hostname = $res_list[4];
			$domain = $res_list[5];
			if (!$domain) { $domain = $default_domain; }
			$gateway = $res_list[6];
			$subnetmask = $res_list[7];
			if (!preg_match('/incomplete/', $res_list[1])) {
				fputs($dhcfile, "    host $hostname.$domain {\n");
				fputs($dhcfile, "      hardware ethernet $mac;\n");
				fputs($dhcfile, "      fixed-address $ip;\n");
				if ($gateway) { fputs($dhcfile, "      option routers $gateway;\n"); }
				if ($subnetmask) { fputs($dhcfile, "      option subnet-mask $subnetmask;\n"); }
				fputs($dhcfile, "    }\n\n");
			}
		}
		if ($network_iface == $wireless_iface) {
			fputs($dhcfile, "  }\n");
		}
	}
	
	fputs($dhcfile, "}\n\n");
}


mysql_close();
fclose ($dhcfile); 

